// ─────────────────────────────────────────────────────────────────────────────
// KPI mock data — values + benchmarks consumed by kpiEngine.
//
// Values are tuned so every role has a deterministic mix of red / yellow /
// green so the hero tile pattern is always meaningful. Benchmark deltas are
// in points (percentage points for % units; raw count for count units).
//
// `meta` carries display hints used by reasonBuilders — e.g. unmarked count.
// ─────────────────────────────────────────────────────────────────────────────

export const KPI_VALUES = {
  teacher: {
    // Top-6 surface mixes 4 reds + 2 greens so the home conveys priority +
    // positive signal:
    //   RED:   attendance_today (-16), tpd_hours (-12), assessment_result (-12), chronic_absentees (-3)
    //   GREEN: attendance_reporting_compliance (+5), student_module_completion (+4)
    // Below-assessment-result is intentionally green so it does NOT duplicate
    // assessment_result on the home (they share the same domain).
    attendance_today:               { value: 72,  meta: { unmarked: 9 } },
    // value MUST match the count in StudentListDetails (kpiInsightDetails.js)
    // and priorityCount MUST match the number of HIGH-risk students in that
    // list (currently Ravi, Dhruv, Harsh = 3). If you change either, change
    // both so the canvas number, the inline list, and the reason agree.
    chronic_absentees:              { value: 6,   meta: { priorityCount: 3 } },
    attendance_reporting_compliance:{ value: 100, meta: {} },
    ews_followup_completed:         { value: 80,  meta: { pendingCount: 1 } },
    assessment_participation:       { value: 95,  meta: { absentCount: 2 } },
    proficiency:                    { value: 60,  meta: {} },
    students_below_proficiency:     { value: 19,  meta: { studentCount: 6, priorityCount: 2 } },
    student_improvement_delta:      { value: 3.5, meta: {} },
    orf_fln_improvement:            { value: 6,   meta: {} },
    student_module_completion:      { value: 82,  meta: { pendingStudents: 5 } },
    tpd_hours:                      { value: 38,  meta: {} },
    students_identified_remediation:{ value: 22,  meta: { identifiedCount: 10 } },
    students_receiving_remediation: { value: 71,  meta: { notStarted: 3 } },
    improvement_after_intervention: { value: 62,  meta: {} },
    gsqac_score:                    { value: 78,  meta: {} },
    // Two A5 quality KPIs the doc lists for teachers (Improvement across
    // cycles % = 11%, Improvement actions completed % = 88%).
    gsqac_improvement_cycles:       { value: 11,  meta: {} },
    improvement_actions_completed:  { value: 88,  meta: { openActions: 2 } },
    same_day_reporting:             { value: 93,  meta: { lateSubmitters: 0 } },
    dashboard_data_lag:             { value: 1.5, meta: {} },
  },
  principal: {
    attendance_today:               { value: 84,  meta: {} },
    chronic_absentees:              { value: 12,  meta: { priorityCount: 4 } },
    schools_below_attendance_benchmark: { value: 0, meta: {} },
    attendance_reporting_compliance:{ value: 96,  meta: {} },
    ews_followup_completed:         { value: 70,  meta: { pendingCount: 6 } },
    assessment_participation:       { value: 89,  meta: { absentCount: 14 } },
    proficiency:                    { value: 67,  meta: {} },
    students_below_proficiency:     { value: 26,  meta: { studentCount: 84, priorityCount: 18 } },
    student_improvement_delta:      { value: 3.2, meta: {} },
    orf_fln_improvement:            { value: 5,   meta: {} },
    reports_generated_downloaded:   { value: 92,  meta: { pendingSchools: 1 } },
    student_module_completion:      { value: 74,  meta: { pendingStudents: 38 } },
    tpd_hours:                      { value: 41,  meta: {} },
    students_identified_remediation:{ value: 21,  meta: { identifiedCount: 71 } },
    students_receiving_remediation: { value: 68,  meta: { notStarted: 17 } },
    improvement_after_intervention: { value: 55,  meta: {} },
    scheme_beneficiary_mapping:     { value: 88,  meta: { unmapped: 6 } },
    payment_completion:             { value: 78,  meta: { pendingPayments: 18 } },
    pending_payments_grievances:    { value: 12,  meta: {} },
    issue_resolution_sla:           { value: 71,  meta: { openOverdue: 5 } },
    repeat_pending_cases:           { value: 3,   meta: {} },
    gsqac_score:                    { value: 73,  meta: {} },
    schools_meeting_quality_benchmark: { value: 62, meta: {} },
    low_performing_schools:         { value: 0,   meta: {} },
    gsqac_improvement_cycles:       { value: 2.1, meta: {} },
    improvement_actions_completed:  { value: 78,  meta: { openActions: 5 } },
    same_day_reporting:             { value: 90,  meta: { lateSubmitters: 2 } },
    dashboard_data_lag:             { value: 1.8, meta: {} },
    pending_issues_cross_system:    { value: 24,  meta: {} },
    repeat_issues_pct:              { value: 11,  meta: {} },
    action_on_ews_flagged:          { value: 72,  meta: { pendingCount: 9 } },
    pm_shri_performance:            { value: 76,  meta: {} },
  },
  crc: {
    attendance_today:               { value: 86,  meta: {} },
    chronic_absentees:              { value: 38,  meta: { priorityCount: 12 } },
    schools_below_attendance_benchmark: { value: 2, meta: {} },
    attendance_reporting_compliance:{ value: 91,  meta: {} },
    ews_followup_completed:         { value: 64,  meta: { pendingCount: 22 } },
    assessment_participation:       { value: 88,  meta: { absentCount: 64 } },
    proficiency:                    { value: 69,  meta: {} },
    students_below_proficiency:     { value: 24,  meta: { studentCount: 312, priorityCount: 62 } },
    student_improvement_delta:      { value: 2.8, meta: {} },
    orf_fln_improvement:            { value: 4,   meta: {} },
    reports_generated_downloaded:   { value: 86,  meta: { pendingSchools: 4 } },
    student_module_completion:      { value: 71,  meta: { pendingStudents: 142 } },
    tpd_hours:                      { value: 39,  meta: {} },
    students_identified_remediation:{ value: 22,  meta: { identifiedCount: 264 } },
    students_receiving_remediation: { value: 63,  meta: { notStarted: 78 } },
    improvement_after_intervention: { value: 52,  meta: {} },
    scheme_beneficiary_mapping:     { value: 84,  meta: { unmapped: 41 } },
    payment_completion:             { value: 73,  meta: { pendingPayments: 88 } },
    pending_payments_grievances:    { value: 22,  meta: {} },
    issue_resolution_sla:           { value: 68,  meta: { openOverdue: 12 } },
    repeat_pending_cases:           { value: 7,   meta: {} },
    gsqac_score:                    { value: 71,  meta: {} },
    schools_meeting_quality_benchmark: { value: 58, meta: {} },
    low_performing_schools:         { value: 3,   meta: {} },
    gsqac_improvement_cycles:       { value: 1.4, meta: {} },
    improvement_actions_completed:  { value: 72,  meta: { openActions: 18 } },
    same_day_reporting:             { value: 86,  meta: { lateSubmitters: 9 } },
    dashboard_data_lag:             { value: 2.1, meta: {} },
    pending_issues_cross_system:    { value: 41,  meta: {} },
    repeat_issues_pct:              { value: 14,  meta: {} },
    action_on_ews_flagged:          { value: 66,  meta: { pendingCount: 31 } },
  },
  beo: {
    attendance_today:               { value: 81,  meta: {} },
    chronic_absentees:              { value: 184, meta: { priorityCount: 42 } },
    schools_below_attendance_benchmark: { value: 7, meta: {} },
    attendance_reporting_compliance:{ value: 84,  meta: {} },
    ews_followup_completed:         { value: 58,  meta: { pendingCount: 86 } },
    assessment_participation:       { value: 86,  meta: { absentCount: 312 } },
    proficiency:                    { value: 62,  meta: {} },
    students_below_proficiency:     { value: 31,  meta: { studentCount: 1820, priorityCount: 412 } },
    student_improvement_delta:      { value: 2.1, meta: {} },
    orf_fln_improvement:            { value: 3,   meta: {} },
    reports_generated_downloaded:   { value: 82,  meta: { pendingSchools: 19 } },
    student_module_completion:      { value: 68,  meta: { pendingStudents: 612 } },
    tpd_hours:                      { value: 36,  meta: {} },
    students_identified_remediation:{ value: 24,  meta: { identifiedCount: 1402 } },
    students_receiving_remediation: { value: 59,  meta: { notStarted: 412 } },
    improvement_after_intervention: { value: 49,  meta: {} },
    scheme_beneficiary_mapping:     { value: 79,  meta: { unmapped: 188 } },
    payment_completion:             { value: 68,  meta: { pendingPayments: 312 } },
    pending_payments_grievances:    { value: 78,  meta: {} },
    issue_resolution_sla:           { value: 63,  meta: { openOverdue: 41 } },
    repeat_pending_cases:           { value: 18,  meta: {} },
    gsqac_score:                    { value: 68,  meta: {} },
    schools_meeting_quality_benchmark: { value: 54, meta: {} },
    low_performing_schools:         { value: 9,   meta: {} },
    gsqac_improvement_cycles:       { value: 0.8, meta: {} },
    improvement_actions_completed:  { value: 64,  meta: { openActions: 88 } },
    same_day_reporting:             { value: 82,  meta: { lateSubmitters: 41 } },
    dashboard_data_lag:             { value: 2.6, meta: {} },
    pending_issues_cross_system:    { value: 142, meta: {} },
    repeat_issues_pct:              { value: 16,  meta: {} },
    action_on_ews_flagged:          { value: 61,  meta: { pendingCount: 122 } },
    dropout_reduction:              { value: 2.1, meta: {} },
    reenrollment_vs_target:         { value: 248, meta: { target: 320 } },
    samagra_shiksha_expenditure:    { value: 71,  meta: {} },
    pm_shri_performance:            { value: 74,  meta: {} },
  },
  state_secretary: {
    attendance_today:               { value: 88,  meta: {} },
    chronic_absentees:              { value: 4820, meta: { priorityCount: 1240 } },
    schools_below_attendance_benchmark: { value: 184, meta: {} },
    attendance_reporting_compliance:{ value: 92,  meta: {} },
    ews_followup_completed:         { value: 66,  meta: { pendingCount: 1840 } },
    assessment_participation:       { value: 91,  meta: { absentCount: 8420 } },
    proficiency:                    { value: 71,  meta: {} },
    students_below_proficiency:     { value: 22,  meta: { studentCount: 48200, priorityCount: 8200 } },
    student_improvement_delta:      { value: 3.4, meta: {} },
    orf_fln_improvement:            { value: 5,   meta: {} },
    reports_generated_downloaded:   { value: 89,  meta: { pendingSchools: 412 } },
    student_module_completion:      { value: 74,  meta: { pendingStudents: 14200 } },
    tpd_hours:                      { value: 42,  meta: {} },
    students_identified_remediation:{ value: 22,  meta: { identifiedCount: 38000 } },
    students_receiving_remediation: { value: 65,  meta: { notStarted: 9200 } },
    improvement_after_intervention: { value: 56,  meta: {} },
    scheme_beneficiary_mapping:     { value: 86,  meta: { unmapped: 4120 } },
    payment_completion:             { value: 81,  meta: { pendingPayments: 6800 } },
    pending_payments_grievances:    { value: 1240, meta: {} },
    issue_resolution_sla:           { value: 74,  meta: { openOverdue: 612 } },
    repeat_pending_cases:           { value: 312, meta: {} },
    gsqac_score:                    { value: 74,  meta: {} },
    schools_meeting_quality_benchmark: { value: 64, meta: {} },
    low_performing_schools:         { value: 142, meta: {} },
    gsqac_improvement_cycles:       { value: 2.4, meta: {} },
    improvement_actions_completed:  { value: 76,  meta: { openActions: 1820 } },
    same_day_reporting:             { value: 89,  meta: { lateSubmitters: 412 } },
    dashboard_data_lag:             { value: 2.0, meta: {} },
    pending_issues_cross_system:    { value: 1842, meta: {} },
    repeat_issues_pct:              { value: 12,  meta: {} },
    action_on_ews_flagged:          { value: 70,  meta: { pendingCount: 2120 } },
    dropout_reduction:              { value: 2.4, meta: {} },
    reenrollment_vs_target:         { value: 8420, meta: { target: 9500 } },
    samagra_shiksha_expenditure:    { value: 78,  meta: {} },
    pm_shri_performance:            { value: 79,  meta: {} },
  },
  parent: {
    child_attendance:           { value: 78,  meta: {} },
    child_proficiency:          { value: 62,  meta: {} },
    child_chronic_absence_flag: { value: 0,   meta: {} },
    child_scholarship_status:   { value: 1,   meta: { statusLabel: 'Approved' } },
    child_namo_docs_pending:    { value: 2,   meta: {} },
  },
  pfms: {
    scheme_beneficiary_mapping:  { value: 86, meta: { unmapped: 4120 } },
    payment_completion:          { value: 81, meta: { pendingPayments: 6800 } },
    pending_payments_grievances: { value: 1240, meta: {} },
    issue_resolution_sla:        { value: 74, meta: { openOverdue: 612 } },
    repeat_pending_cases:        { value: 312, meta: {} },
  },
}

export const BENCHMARKS = {
  state_avg: {
    attendance_today: 88,
    attendance_reporting_compliance: 95,
    ews_followup_completed: 78,
    assessment_participation: 92,
    proficiency: 72,
    students_below_proficiency: 21,
    student_improvement_delta: 3.0,
    orf_fln_improvement: 5,
    reports_generated_downloaded: 90,
    student_module_completion: 78,
    students_identified_remediation: 22,
    students_receiving_remediation: 70,
    improvement_after_intervention: 60,
    scheme_beneficiary_mapping: 88,
    payment_completion: 84,
    issue_resolution_sla: 76,
    gsqac_score: 76,
    schools_meeting_quality_benchmark: 66,
    gsqac_improvement_cycles: 2.5,
    improvement_actions_completed: 80,
    same_day_reporting: 92,
    repeat_issues_pct: 10,
    action_on_ews_flagged: 76,
    dropout_reduction: 2.2,
    samagra_shiksha_expenditure: 80,
    pm_shri_performance: 78,
  },
  school_avg: {
    'Sardar Patel Prathmik Shala': {
      chronic_absentees: 3,
    },
  },
  cluster_avg: {
    MADHAPAR: {},
  },
  fixed_target: {
    tpd_hours: 50,
    dashboard_data_lag: 2,
    child_attendance: 90,
    child_proficiency: 70,
  },
}
